apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: jamesfloatingmarket1508/mss-currency-conversion-k8s:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mss-currency-conversion-k8s
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer

