

resilience4j.retry:
    instances:
        retry-abc:
            maxAttempts: 5
            waitDuration: 1s
            enableExponentialBackoff: true



resilience4j.circuitbreaker:
    instances:
        circuitBreaker-def:
            failureRateThreshold: 50
          
           
