
spring:
    application:
        name: currency-exchange-service
    h2:
        console:
            enabled: 'true'
    datasource:
        url: jdbc:h2:mem:currencyExchangeDB
    jpa:
        defer-datasource-initialization: 'true   '
        show-sql: 'true'

server:
    port: '8000'
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    tracing:
        sampling:
            probability: '1.0'



