


INSERT INTO CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO)  VALUES (1000, 23500, '', 'USD', 'VND');

INSERT INTO CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO)  VALUES (1001, 3.64, '', 'USD', 'THB');

INSERT INTO CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO)  VALUES (1002, 0.79, '', 'USD', 'GBP');

